# Uncomment the next line to define a global platform for your project
platform :ios, '13.4'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/expo-modules-core/scripts/autolinking'
require_relative '../node_modules/expo/scripts/autolinking'

install! 'cocoapods', :deterministic_uuids => false

target 'goldsilverappios' do
  config = use_native_modules!

  # Expo modules
  use_expo_modules!

  # React Native
  config.use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

